version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: todo.api
    build:
      context: .
      dockerfile: WebApi/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"

  masterDb:
    image: postgres:latest
    container_name: todo.database
    environment:
      - POSTGRES_DB=todo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/todo-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  products.cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'